services:
  detection:
    build: .
    devices:
      - "/dev/video0:/dev/video0"
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

